### ISSUE TITLE
ensure actions/checkout fetches tags

### ISSUE THREAD

**Issue by behrisch** [eclipse-sumo/sumo#16202]
currently our github actions checkout look sometimes like this:
```
    - name: Cloning SUMO
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
```
and sometimes have an extra
```
    - name: Fetching SUMO tags
      run: git fetch --tags --force
```

The last release build did not work properly (no proper version in the build associated with the tag) so it might be that the second step is actually necessary but we should recheck and document(!) this. Further things to inspect here are whether

```
      with:
        fetch-tags: true
```
and 
```
      with:
        filter: tree:0
```
improve the situation (or reduce the checkout time).

see https://github.com/actions/checkout/issues/1467 and https://github.com/actions/checkout/issues/1471
